# Generated by Django 2.2.4 on 2020-11-10 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('min_price', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('lifecycle', models.CharField(choices=[('A', 'Active'), ('B', 'Banned'), ('D', 'Due'), ('X', 'Adjudicated')], max_length=1)),
                ('lock', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen')),
                ('linkV', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('cuerpo_noticia', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=60, verbose_name='Autor')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('desc', models.TextField()),
                ('tipolib', models.CharField(choices=[('Poesia', 'Poesia'), ('Relato corto', 'Relato corto'), ('Comic', 'Comic')], max_length=30, verbose_name='Tipo de Libro')),
                ('portada', models.ImageField(upload_to='', verbose_name='Portada')),
                ('text', models.FileField(blank=True, null=True, upload_to='', verbose_name='Texto del libro')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('comentario', models.TextField(verbose_name='comentario')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('W', 'Wining'), ('L', 'Losing')], max_length=1)),
                ('auct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
