version: "3.7"

services:
  app:
    build: app
    container_name: MASK-gunicorn
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 MASKWEB.wsgi:application"

  nginx:
    image: nginx:1.17
    container_name: MASK-ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
